version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["serve", "-p", "8080", "-d", "./data"]
    networks:
      - s3fs-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  s3fs-network:
    driver: bridge