version: '3.1'

services:
  server:
    image: evalsocket/s3fs-cli:59fc6c2-dirty
    ports:
      - "8080:8080"
    command: ["serve", "--log-level", "debug"]
    networks:
      - s3fs-network
    restart: unless-stopped

networks:
  s3fs-network:
    driver: bridge