apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3fs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s3fs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}