syntax = "proto3";

package cloud.v1;

import "validate/validate.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service DataNodeService {
    rpc Ping(PingRequest) returns (PingResponse);
    rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
    rpc PutData(DataNodePutRequest) returns (DataNodeWriteStatus);
    rpc GetData(DataNodeGetRequest) returns (DataNodeData);
}

service StorageService {
    rpc Upload(UploadRequest) returns (UploadResponse);
    rpc Download(DownloadRequest) returns (DownloadResponse);
    rpc Delete(DeleteRequest) returns (DeleteResponse);
    rpc ListObjects(ListObjectsRequest) returns (ListObjectsResponse);
    rpc Ping(PingRequest) returns (PingResponse);
    rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
}

message DataNodePutRequest {
    string block_id = 1;
    string data = 2;
    repeated NodeAddress replication_nodes = 3;
}

message DataNodeWriteStatus {
    bool status = 1;
}

message DataNodeGetRequest {
    string block_id = 1;
}

message DataNodeData {
    string data = 1;
}

message NodeAddress {
    string host = 1;
    string service_port = 2;
}

// Define the request and response messages for each method
message UploadRequest {
    string object_key = 2;
    bytes data = 3;
}

message UploadResponse {
    string message = 1;
}

message DownloadRequest {
    string object_key = 2;
}

message DownloadResponse {
    bytes data = 1;
}

message DeleteRequest {
    string object_key = 2;
}

message DeleteResponse {
    string message = 1;
}

message ListObjectsRequest {
}

message ListObjectsResponse {
    repeated string object_keys = 1;
}

message PingRequest {
    string host = 1;
    string port = 2;
}

message PingResponse {
    bool ack = 1;
}

message HeartbeatRequest {
}

message HeartbeatResponse {
    string status = 1;
}