syntax = "proto3";

package cloud.v1;

import "validate/validate.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";


service StorageService {
    rpc Upload(UploadRequest) returns (UploadResponse);
    rpc Get(GetRequest) returns (GetResponse);
    rpc ListObjects(ListObjectsRequest) returns (ListObjectsResponse);
    rpc ReDistribute(ReDistributeRequest) returns (ReDistributeResponse);
    rpc Delete(DeleteRequest) returns (DeleteResponse);
}

message DeleteRequest {
    string object_key = 1 [(validate.rules).string = {min_len: 1, max_len: 100}];
}

message DeleteResponse {
    string message = 1;
}

message ReDistributeRequest {
    string data_node_uri = 1; // Corresponds to DataNodeUri in your struct
}

message ReDistributeResponse {
    string message = 1; // You can customize this field as needed
}

message GetRequest {
    string object_key = 1 [(validate.rules).string = {min_len: 1, max_len: 100}];
}

message GetResponse {
    bytes data = 1;
}

// Define the request and response messages for each method
message UploadRequest {
    uint32 file_size = 1;
    string object_key = 2 [(validate.rules).string = {min_len: 1, max_len: 100}];
    bytes data = 3;
}

message UploadResponse {
    string message = 1;
}

message ListObjectsRequest {
}

message ListObjectsResponse {
    repeated string object_keys = 1;
}
