// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	cloudv1 "s3fs/pkg/gen/cloud/v1"

	connect "connectrpc.com/connect"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

type StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageService) EXPECT() *StorageService_Expecter {
	return &StorageService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, req
func (_m *StorageService) Delete(ctx context.Context, req *connect.Request[cloudv1.DeleteRequestMsg]) (*connect.Response[cloudv1.DeleteStatusMsg], error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *connect.Response[cloudv1.DeleteStatusMsg]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.DeleteRequestMsg]) (*connect.Response[cloudv1.DeleteStatusMsg], error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.DeleteRequestMsg]) *connect.Response[cloudv1.DeleteStatusMsg]); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[cloudv1.DeleteStatusMsg])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connect.Request[cloudv1.DeleteRequestMsg]) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StorageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *connect.Request[cloudv1.DeleteRequestMsg]
func (_e *StorageService_Expecter) Delete(ctx interface{}, req interface{}) *StorageService_Delete_Call {
	return &StorageService_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *StorageService_Delete_Call) Run(run func(ctx context.Context, req *connect.Request[cloudv1.DeleteRequestMsg])) *StorageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*connect.Request[cloudv1.DeleteRequestMsg]))
	})
	return _c
}

func (_c *StorageService_Delete_Call) Return(_a0 *connect.Response[cloudv1.DeleteStatusMsg], _a1 error) *StorageService_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageService_Delete_Call) RunAndReturn(run func(context.Context, *connect.Request[cloudv1.DeleteRequestMsg]) (*connect.Response[cloudv1.DeleteStatusMsg], error)) *StorageService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, req, stream
func (_m *StorageService) Get(ctx context.Context, req *connect.Request[cloudv1.GetObjectRequest], stream *connect.ServerStream[cloudv1.GetObjectResponse]) error {
	ret := _m.Called(ctx, req, stream)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.GetObjectRequest], *connect.ServerStream[cloudv1.GetObjectResponse]) error); ok {
		r0 = rf(ctx, req, stream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StorageService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - req *connect.Request[cloudv1.GetObjectRequest]
//   - stream *connect.ServerStream[cloudv1.GetObjectResponse]
func (_e *StorageService_Expecter) Get(ctx interface{}, req interface{}, stream interface{}) *StorageService_Get_Call {
	return &StorageService_Get_Call{Call: _e.mock.On("Get", ctx, req, stream)}
}

func (_c *StorageService_Get_Call) Run(run func(ctx context.Context, req *connect.Request[cloudv1.GetObjectRequest], stream *connect.ServerStream[cloudv1.GetObjectResponse])) *StorageService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*connect.Request[cloudv1.GetObjectRequest]), args[2].(*connect.ServerStream[cloudv1.GetObjectResponse]))
	})
	return _c
}

func (_c *StorageService_Get_Call) Return(_a0 error) *StorageService_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_Get_Call) RunAndReturn(run func(context.Context, *connect.Request[cloudv1.GetObjectRequest], *connect.ServerStream[cloudv1.GetObjectResponse]) error) *StorageService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Heartbeat provides a mock function with given fields: ctx, req
func (_m *StorageService) Heartbeat(ctx context.Context, req *connect.Request[cloudv1.HeartbeatRequestMsg]) (*connect.Response[cloudv1.HeartbeatResponseMsg], error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Heartbeat")
	}

	var r0 *connect.Response[cloudv1.HeartbeatResponseMsg]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.HeartbeatRequestMsg]) (*connect.Response[cloudv1.HeartbeatResponseMsg], error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.HeartbeatRequestMsg]) *connect.Response[cloudv1.HeartbeatResponseMsg]); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[cloudv1.HeartbeatResponseMsg])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connect.Request[cloudv1.HeartbeatRequestMsg]) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_Heartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heartbeat'
type StorageService_Heartbeat_Call struct {
	*mock.Call
}

// Heartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - req *connect.Request[cloudv1.HeartbeatRequestMsg]
func (_e *StorageService_Expecter) Heartbeat(ctx interface{}, req interface{}) *StorageService_Heartbeat_Call {
	return &StorageService_Heartbeat_Call{Call: _e.mock.On("Heartbeat", ctx, req)}
}

func (_c *StorageService_Heartbeat_Call) Run(run func(ctx context.Context, req *connect.Request[cloudv1.HeartbeatRequestMsg])) *StorageService_Heartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*connect.Request[cloudv1.HeartbeatRequestMsg]))
	})
	return _c
}

func (_c *StorageService_Heartbeat_Call) Return(_a0 *connect.Response[cloudv1.HeartbeatResponseMsg], _a1 error) *StorageService_Heartbeat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageService_Heartbeat_Call) RunAndReturn(run func(context.Context, *connect.Request[cloudv1.HeartbeatRequestMsg]) (*connect.Response[cloudv1.HeartbeatResponseMsg], error)) *StorageService_Heartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req
func (_m *StorageService) List(ctx context.Context, req *connect.Request[cloudv1.ListObjectsRequest]) (*connect.Response[cloudv1.ListObjectsResponse], error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *connect.Response[cloudv1.ListObjectsResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.ListObjectsRequest]) (*connect.Response[cloudv1.ListObjectsResponse], error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connect.Request[cloudv1.ListObjectsRequest]) *connect.Response[cloudv1.ListObjectsResponse]); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[cloudv1.ListObjectsResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connect.Request[cloudv1.ListObjectsRequest]) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type StorageService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *connect.Request[cloudv1.ListObjectsRequest]
func (_e *StorageService_Expecter) List(ctx interface{}, req interface{}) *StorageService_List_Call {
	return &StorageService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *StorageService_List_Call) Run(run func(ctx context.Context, req *connect.Request[cloudv1.ListObjectsRequest])) *StorageService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*connect.Request[cloudv1.ListObjectsRequest]))
	})
	return _c
}

func (_c *StorageService_List_Call) Return(_a0 *connect.Response[cloudv1.ListObjectsResponse], _a1 error) *StorageService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageService_List_Call) RunAndReturn(run func(context.Context, *connect.Request[cloudv1.ListObjectsRequest]) (*connect.Response[cloudv1.ListObjectsResponse], error)) *StorageService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, stream
func (_m *StorageService) Upload(ctx context.Context, stream *connect.ClientStream[cloudv1.UploadRequestMsg]) (*connect.Response[cloudv1.UploadResponseMsg], error) {
	ret := _m.Called(ctx, stream)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *connect.Response[cloudv1.UploadResponseMsg]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connect.ClientStream[cloudv1.UploadRequestMsg]) (*connect.Response[cloudv1.UploadResponseMsg], error)); ok {
		return rf(ctx, stream)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connect.ClientStream[cloudv1.UploadRequestMsg]) *connect.Response[cloudv1.UploadResponseMsg]); ok {
		r0 = rf(ctx, stream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connect.Response[cloudv1.UploadResponseMsg])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connect.ClientStream[cloudv1.UploadRequestMsg]) error); ok {
		r1 = rf(ctx, stream)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type StorageService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - stream *connect.ClientStream[cloudv1.UploadRequestMsg]
func (_e *StorageService_Expecter) Upload(ctx interface{}, stream interface{}) *StorageService_Upload_Call {
	return &StorageService_Upload_Call{Call: _e.mock.On("Upload", ctx, stream)}
}

func (_c *StorageService_Upload_Call) Run(run func(ctx context.Context, stream *connect.ClientStream[cloudv1.UploadRequestMsg])) *StorageService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*connect.ClientStream[cloudv1.UploadRequestMsg]))
	})
	return _c
}

func (_c *StorageService_Upload_Call) Return(_a0 *connect.Response[cloudv1.UploadResponseMsg], _a1 error) *StorageService_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageService_Upload_Call) RunAndReturn(run func(context.Context, *connect.ClientStream[cloudv1.UploadRequestMsg]) (*connect.Response[cloudv1.UploadResponseMsg], error)) *StorageService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
