apiVersion: v2
name: s3fs
description: A Helm chart for deploying the s3fs application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - s3fs
  - s3
maintainers:
  - name: Yuvraj Yadav
    email: evalsocket@gmail.com
